name: cocktailr
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cached_network_image: 3.3.1
  cupertino_icons: 1.0.6
  equatable: 2.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: 2.5.1
  go_router: 14.1.3
  http: 1.2.1
  json_annotation: 4.9.0
  theme_tailor_annotation: 3.0.1
  vector_graphics: 1.1.11+1

dev_dependencies:
  build_runner:
  custom_lint: 0.6.4
  flutter_lints: 3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: 6.8.0
  riverpod_lint: 2.3.10
  theme_tailor: 3.0.1
  vector_graphics_compiler: 1.1.11+1

flutter:
  assets:
    - path: assets/icons/
      transformers:
        - package: vector_graphics_compiler

  fonts:
    - family: BodoniModa
      fonts:
        - asset: assets/fonts/bodoni_moda/BodoniModa_9pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/bodoni_moda/BodoniModa_9pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/bodoni_moda/BodoniModa_9pt-SemiBold.ttf
          weight: 600
    - family: SFPro
      fonts:
        - asset: assets/fonts/sf_pro/SF_Pro_Text_Light.otf
          weight: 300
        - asset: assets/fonts/sf_pro/SF_Pro_Text_Regular.otf
          weight: 400

  uses-material-design: true

