### Test ###
desc "Run all tests that don't require a physical device (= that run on a virtual machine). This includes unit, widget and golden tests."
lane :run_vm_tests do
  Dir.chdir("..") do
    sh("fvm flutter test --machine")
  end
end

### Android ###
platform :android do
  ### Build ###
  desc "Build Android debug"
  lane :build_debug do
    Dir.chdir("..") do
      sh("fvm flutter build apk --debug")
    end
  end

  desc "Build Android release"
  lane :build_release do
    Dir.chdir("..") do
      sh("fvm flutter build apk --release")
    end
  end

  ### Distribute ###
  desc "Distribute to Firebase App Distribution"
  lane :distribute_firebase do
    Dir.chdir("..") do
      android_artifact_path = File.expand_path("./build/app/outputs/flutter-apk/app-release.apk", Dir.pwd)
      service_credentials_file = File.expand_path("./FIREBASE_APP_DISTRIBUTION_SERVICE_ACCOUNT_KEY.json", Dir.pwd)

      firebase_app_distribution(
        app: "1:30086613147:android:9d5c7c6b5005dcdddb1e3e",
        service_credentials_file: service_credentials_file,
        groups: "in-the-pocket",
        android_artifact_type: "APK",
        android_artifact_path: android_artifact_path,
      )
    end
  end
end

### iOS ###
platform :ios do
  ### Build ###
  desc "Build iOS debug (for simulator)"
  lane :build_debug do
    Dir.chdir("..") do
      sh("fvm flutter build ios --debug --simulator")
    end
  end

  desc "Build iOS release"
  lane :build_release do
    Dir.chdir("..") do
      sh("fvm flutter build ipa --release --export-options-plist ios/Runner/ExportOptions.plist")
    end
  end

  ### Distribute ###
  desc "Distribute to Firebase App Distribution"
  lane :distribute_firebase do
    Dir.chdir("..") do
      ipa_path = File.expand_path("./build/ios/ipa/cocktailr.ipa", Dir.pwd)
      service_credentials_file = File.expand_path("./FIREBASE_APP_DISTRIBUTION_SERVICE_ACCOUNT.json", Dir.pwd)

      firebase_app_distribution(
        app: "1:30086613147:ios:6d5b0b44109feea8db1e3e",
        service_credentials_file: service_credentials_file,
        groups: "in-the-pocket",
        ipa_path: ipa_path,
      )
    end
  end
end
