name: default-workflow
on: [push]
# TODO:
# on:
#   push:
#     branches:
#       - main
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.1" # TODO: keep this somewhere where it's easy to change

      - name: Install gems
        run: bundle install

      - name: Install FVM
        run: curl -fsSL https://fvm.app/install.sh | bash

      - name: Set up FVM
        run: fvm use

      - name: Run virtual machine tests
        run: bundle exec fastlane run_vm_tests

  build_android:
    name: Build Android debug
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.1" # TODO: keep this somewhere where it's easy to change

      - name: Install gems
        run: bundle install

      - name: Install FVM
        run: curl -fsSL https://fvm.app/install.sh | bash

      - name: Set up FVM
        run: fvm use

      - name: Decode and save google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 -d > ./android/app/google-services.json

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build debug
        run: bundle exec fastlane android build_debug

  build_ios:
    name: Build iOS debug
    runs-on: macos-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.1" # TODO: keep this somewhere where it's easy to change

      - name: Install gems
        run: bundle install

      - name: Install FVM
        run: |
          brew tap leoafarias/fvm
          brew install fvm

      - name: Set up FVM
        run: fvm use

      - name: Decode and save GoogleServices-Info.plist
        run: echo "${{ secrets.GOOGLESERVICE_INFO_PLIST }}" | base64 -d > ./ios/Runner/GoogleService-Info.plist

      - name: Build debug
        run: bundle exec fastlane ios build_debug

      # - name: Decode and save FIREBASE_APP_DISTRIBUTION_SERVICE_ACCOUNT.json
      #   run: echo "${{ secrets.FIREBASE_APP_DISTRIBUTION_SERVICE_ACCOUNT_JSON }}" | base64 -d > ./FIREBASE_APP_DISTRIBUTION_SERVICE_ACCOUNT.json